### ISSUE TITLE
Build keretrendszer + CI beüzemelése

### ISSUE THREAD

**Issue by mszrsblnt** [BME-MIT-IET/iet-hf-2024-austriacki-pingwin#1]
Build keretrendszer: Maven
CI: GitHub Actions

**Comment by vszkb** [comment]
#3 Build and CI: @mszrsblnt Hozzáadtam a maven build keretrendszert a projekthez, kérlek ellenőrizd a pull-requestet.

**Comment by mszrsblnt** [comment]
> #3 Build and CI: @mszrsblnt Hozzáadtam a maven build keretrendszert a projekthez, kérlek ellenőrizd a pull-requestet.

Kedves @vszkb! Javítottam a pom.xml fájlban a maven buildet, kérlek végezd el a dependency tree frissítését! Köszi!

**Comment by vszkb** [comment]
#3 Kedves @mszrsblnt bövítettem az ágat a feladat leírásával, valamint ellenőriztem, amit kértél. Megkérnénk @NMSDomi -ot hogy review-olja a pull-request-et, már meghívtam hozzá.

**Comment by mszrsblnt** [comment]
@vszkb @NMSDomi 
A SonarCloud integrációjával problémák akadtak, így a projekt struktúrát át kéne építeni, hogy megfeleljen a [Maven alapértelmezéseknek](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html).

**Comment by vszkb** [comment]
A projekt struktúra követve a maven ajánlást át lett építve a #7 pull-requestben.
