### ISSUE TITLE
SonarCloud hibák javítása

### ISSUE THREAD

**Issue by vszkb** [BME-MIT-IET/iet-hf-2024-austriacki-pingwin#11]
A SonarCloud által jelzett hibák javítása, ellenőrzése

**Comment by mszrsblnt** [comment]
@vszkb @NMSDomi 
Elkezdek dolgozni a **High Reliability** problémákon. 
![image](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/assets/94174869/a3def7d6-5ab0-46a1-a579-06e2e308ef46)

**Comment by mszrsblnt** [comment]
Elkezdtem dolgozni a **Medium Reliability** problémákon is.
![image](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/assets/94174869/654a5c31-8509-4b18-a4ef-4b124daf6767)

**Comment by NMSDomi** [comment]
![image](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/assets/94184487/aeb02b87-6a0e-4e9c-b24a-b0de764f5ad2)
Szép munka!

**Comment by vszkb** [comment]
Én a _high severity_ problémák közül a csapat által relevánsnak gondoltakat javítottam, valamint a clean code-ot megsértő hibákat néztem meg. A javítások során a kód manuális analízisát is elvégeztem.
