### ISSUE TITLE
Exploratory testing

### ISSUE THREAD

**Issue by danbronzebeard** [BME-MIT-IET/iet-hf-2024-austriacki-pingwin#13]

**Comment by danbronzebeard** [comment]
[Exploratory testing.pdf](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/files/15366841/Exploratory.testing.pdf)
Elkészültem az exploratory testing-gel, @NMSDomi kérlek ellenőrizd és ha szerinted megfelel, zárd le az issue-t!

**Comment by NMSDomi** [comment]
A dokumentációt ellenőriztem, ezzel kapcsolatban az észrevételeim:
- 2b, pumpa elrontása: Ez valóban egy végrehajthatatlan akció ezen a mezőn, ennek javítását kérlek végezd el a branchen, amit létrehozok
- csúszós/ragadós csövek: A szabotált csövek vizuális reprezentációjának hiánya megrendelői kérés a játék nehézségének érdekében
- 4ab, cső egyszerre két szerelő kezében: A tesztet én is végrehajtottam és nem tapasztaltam logikába ütköző problémát, a szabotőr csak azután tudott lelépni egy csőről, amint az csatlakoztatva volt legalább 1 aktív elemhez, míg szerelők kezében volt, addig nem
