### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása

### ISSUE THREAD

**Issue by NMSDomi** [BME-MIT-IET/iet-hf-2024-austriacki-pingwin#4]

**Comment by NMSDomi** [comment]
A tesztek tervezését magamnak jelölöm ki feladatnak a "Saboteur" karakter elérhető műveleteinek funkcionalitására. A tervek pontos megvalósításának leírása után @agotabenjoe téged szeretnélek megkérni ezeknek az elvégzésére a dokumentációban foglaltak alapján majd kiértékelésére.

**Comment by NMSDomi** [comment]
@agotabenjoe elkészült a tesztelési terv, kérlek a dokumentumban foglaltak alapján végezd el azokat!

[Manuális teszt - Saboteur.docx](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/files/15320159/Manualis.teszt.-.Saboteur.docx)
[Manuális teszt - Saboteur.pdf](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/files/15320160/Manualis.teszt.-.Saboteur.pdf)

**Comment by agotabenjoe** [comment]
@NMSDomi

Elvégeztem a teszteket. Többnyire jól működött minden. A hibákat jeleztem.

[Manualis.teszt.-.Saboteur.docx](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/files/15333797/Manualis.teszt.-.Saboteur.docx)
[Manualis.teszt.-.Saboteur.pdf](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/files/15333806/Manualis.teszt.-.Saboteur.pdf)

**Comment by NMSDomi** [comment]
@agotabenjoe köszönöm a munkádat! A teszt eredményeit figyelembevéve kiértékelem azt.

**Comment by NMSDomi** [comment]
A végrehajtott tesztek kiértékelésre kerültek és a végleges konklúzió szerint a Saboteur karakakter az elvártnak megfelelően működik. Az észrevételek feljegyzésre kerültek.
[Manuális teszt - Saboteur - FINAL.pdf](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/files/15340134/Manualis.teszt.-.Saboteur.-.FINAL.pdf)

Ezzel a tesztfolyamatot lezártnak tekintem és szeretném megkérni @danbronzebeard, hogy nézze át, ha mindent hiánytalannak tekint zárja le az issue-t!

**Comment by danbronzebeard** [comment]
A munkát átnéztem, jól érthető (tiszta és részletes) és átfogó. Nem találtam benne kivetni valót.
