### ISSUE TITLE
BDD tesztek készítése 

### ISSUE THREAD

**Issue by agotabenjoe** [BME-MIT-IET/iet-hf-2024-austriacki-pingwin#8]
A tesztek tervezése és implementálás az én feladatom. A Pipe osztály és a vele kapcsolatos mozgásbeli funkciókat fogom tesztelni. Ellenőrizni @NMSDomi fog.

[User Stories.pdf](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/files/15334420/User.Stories.pdf)

**Comment by agotabenjoe** [comment]
A mozgáshoz tartozó tesztek elkészültek és lefutnak. 
[ide tartozó](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/commit/46103291d6bed5d6529adb0303f2e0abc4fbdad1)

**Comment by agotabenjoe** [comment]
@NMSDomi-al ellenőrizzük a teszteket.

**Comment by NMSDomi** [comment]
@agotabenjoe a mozgáshoz köthető funkciók tesztelését megfelelőnek találtam, haladhatsz tovább! :)

**Comment by agotabenjoe** [comment]
Következőnek a pumpa lehelyezéssel és cső áthelyezéssel kapcsolatos funkciókhoz írok teszteket. Ezeket építési vagyis building feature-öknek neveztem el.

**Comment by agotabenjoe** [comment]
Befejeztem az építésre vonatkozó tesztek készítését. @NMSDomi kérlek ellenőrizd őket!

ide tartozó kommitok:
[1](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/commit/cf82763e9a2fb484a32280490b07e91368e1ce7b)
[2](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/commit/879417d84165f466c3baa7bc60f1addf948baf56)
[3](https://github.com/BME-MIT-IET/iet-hf-2024-austriacki-pingwin/commit/a269f4f725f5b411312e6abb69fce48a666f6e15)

**Comment by NMSDomi** [comment]
@agotabenjoe a teszteket átnéztem, működésük az elvártnak tekinthetőek, kérlek hozz létre pull requestet!
